language: R
cache: packages
sudo: required

env:
matrix:
    include:
        - os: linux
          r: release
          dist: trusty # 14.04
          env: R_CODECOV=true
        - os: linux
          r: devel
          dist: trusty
        - os: linux
          r: oldrel
          dist: trusty
        - os: osx
          r: release
          before_install: ''
          disable_homebrew: true
          #- os: osx
          #r: devel
          #before_install: ''
          #disable_homebrew: true
      allow_failures: # TODO: Remove if it passes
        - os: osx
          r: release
          before_install: ''
          disable_homebrew: true

r_check_args: --as-cran --run-donttest

r_packages:
    - covr

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

after_success:
  - Rscript -e 'covr::codecov()'

before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
  on:
      os: linux
      r: release
