language: R
cache: packages

r_check_args: --as-cran --run-donttest

r_packages:
    - covr

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

after_success:
  - Rscript -e 'covr::codecov()'

